<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>    
    <Version>1.0.0</Version>
    <Product>Trifoia.VideoPlayer</Product>
    <Authors>Trifoia</Authors>
    <Company>Trifoia</Company>
    <Description>FOSS Video Player from Trifoia</Description>
    <Copyright>Trifoia</Copyright>
    <AssemblyName>Trifoia.Module.VideoPlayer.Shared.Oqtane</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oqtane.Shared" Version="6.1.0" />
  </ItemGroup>

</Project>
