<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Version>1.0.0</Version>
		<Authors>Trifoia</Authors>
		<Company>Trifoia</Company>
		<Description>FOSS Video Player from Trifoia</Description>
		<Product>Trifoia.VideoPlayer</Product>
		<Copyright>Trifoia</Copyright>
		<AssemblyName>Trifoia.Module.VideoPlayer.Client.Oqtane</AssemblyName>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.1" />
		<PackageReference Include="System.Net.Http.Json" Version="9.0.1" />

		<PackageReference Include="MudBlazor" Version="8.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BlazoredVideo\src\Blazored.Video\Blazored.Video.csproj" />
		<ProjectReference Include="..\Shared\Trifoia.Module.VideoPlayer.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Oqtane.Client" Version="6.1.0" />
		<PackageReference Include="Oqtane.Shared" Version="6.1.0" />
	</ItemGroup>

	<PropertyGroup>
		<!-- there may be other elements here -->
		<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

</Project>
